// AUTO-GENERATED — DO NOT EDIT THIS FILE.
//
// Generated from github.com/kayushkin/project-store @ 3dab06e952a55cb3aafdd07b9bcdb6c16961e2e4
// Source of truth: the Go types named in tygo.yaml.
// To regenerate: ./generate-ts.sh
//
// Any manual changes will be overwritten on the next generation run.

// Code generated by tygo. DO NOT EDIT.

//////////
// source: rollup.go

/**
 * ProjectCard is a card kanban-store links to the project.
 */
export interface ProjectCard {
  card_id: string;
  title: string;
  /**
   * Status is noteboard's: open, done or archived.
   */
  status: string;
  /**
   * WorkState is kanban-store's shared state for the card, from the column
   * it was last moved into on any board; "" when that column maps to none.
   */
  work_state: string;
}
/**
 * RepoRollup is where one of the project's repos stands.
 */
export interface RepoRollup {
  repo_store_id: number /* int64 */;
  name: string;
  /**
   * UnmergedBranches are local branches the default branch does not contain.
   */
  unmerged_branches: UnmergedBranch[];
  /**
   * LatestDeploy is nil when the ledger has no deploy of the repo.
   */
  latest_deploy?: Deploy;
}
/**
 * UnmergedBranch is a branch whose work has not landed.
 */
export interface UnmergedBranch {
  name: string;
  head_sha: string;
  committed_at: number /* int64 */;
  worktree_path: string;
  session_ids: string[];
}
/**
 * Deploy is a row of repo-store's deploy ledger, as it gives it.
 */
export interface Deploy {
  commit_sha: string;
  deployed_by: string;
  created_at: number /* int64 */;
}
/**
 * Rollup is a project with everything worked out from what it owns.
 */
export interface Rollup {
  project: Project;
  children: Project[];
  links: Link[];
  cards: ProjectCard[];
  /**
   * CardsByWorkState counts the open cards by shared state; "unmapped" counts
   * those whose column maps to none.
   */
  cards_by_work_state: { [key: string]: number /* int */};
  repos: RepoRollup[];
}

//////////
// source: store.go

/**
 * Project is a project's own fields.
 */
export interface Project {
  id: string;
  name: string;
  kind: string;
  parent_id: string;
  goal: string;
  done_when: string;
  stage: string;
  /**
   * SpendTargetShare is nil when nobody set a target.
   */
  spend_target_share?: number /* float64 */;
  created_by: string;
  created_at: number /* int64 */;
  updated_at: number /* int64 */;
  archived_at: number /* int64 */;
}
/**
 * Link is one thing a project owns.
 */
export interface Link {
  id: number /* int64 */;
  project_id: string;
  entity_type: string;
  entity_ref: string;
  label: string;
  note: string;
  created_by: string;
  created_at: number /* int64 */;
}
/**
 * Change is one recorded change to a project's field.
 */
export interface Change {
  id: number /* int64 */;
  project_id: string;
  field: string;
  old_value: string;
  new_value: string;
  changed_by: string;
  changed_at: number /* int64 */;
}
/**
 * Store is the SQLite database.
 */
export interface Store {
}
/**
 * ProjectFields are the fields a caller sets on create or patch. A nil field
 * is left as it is (on create: its default).
 */
export interface ProjectFields {
  Name?: string;
  Kind?: string;
  ParentID?: string;
  Goal?: string;
  DoneWhen?: string;
  Stage?: string;
  SpendTargetShare?: number /* float64 */ | undefined;
}
/**
 * ProjectFilter narrows Projects.
 */
export interface ProjectFilter {
  Query: string;
  Kind: string;
  ParentID: string;
  IncludeArchived: boolean;
}
/**
 * LinkFilter narrows Links. Zero fields do not filter.
 */
export interface LinkFilter {
  ProjectID: string;
  EntityType: string;
  EntityRef: string;
}

//////////
// source: vocabulary.go
/*
Package projectstore keeps projects: what each is for, and what it owns in
other stores, by those stores' ids. What happens in a project — its cards,
sessions, branches, deploys — is not stored here but worked out on request
from what it owns.
*/

/**
 * Kinds of project. A project can be finished; a stream never is.
 */
export const KindProject = "project";
/**
 * Kinds of project. A project can be finished; a stream never is.
 */
export const KindStream = "stream";
/**
 * DefaultStage is a new project's stage when none is given.
 */
export const DefaultStage = "idea";
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntityRepo = "repo"; // repo-store's numeric id
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntityBoard = "board"; // kanban-store board uuid
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntitySchedulerJob = "scheduler_job"; // scheduler's numeric job id
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntityService = "service"; // healthcheck's check name, its key there
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntityPrincipal = "principal"; // principal-store id, principal_000001
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntityNote = "note"; // noteboard item uuid: a decision, a design
/**
 * Entity types a project can own, and the store each id belongs to.
 */
export const EntitySession = "session"; // llm-bridge-server session id, br_…
/**
 * EntityTypeInfo describes a linkable entity type.
 */
export interface EntityTypeInfo {
  type: string;
  service: string;
  meaning: string;
}
